name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Released Version
        required: true
        default: latest

permissions:
  id-token: write
  contents: write
  actions: write
  issues: write

env:
  ECR_REPOSITORY: 2002122067-product
  AWS_ACCOUNT: 694030593525

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      image_digest: ${{ steps.docker.outputs.image_digest }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GithubActionsRole

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build with Gradle
        env:
          ECR_IMAGE_PATH: '${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ inputs.version }}'
        run: ./gradlew clean jib --image=${{ env.ECR_IMAGE_PATH }}